version: "3.9"

services:
  db:
    image: postgres:15
    container_name: resume_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: resume_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://your_user:your_password@db/resume_db
      - JWT_PRIVATE_KEY_PATH=/app/certs/jwt-private-key.pem
      - JWT_PUBLIC_KEY_PATH=/app/certs/jwt-public-key.pem
    volumes:
      - ./certs:/app/certs
      - .:/app

volumes:
  db_data:
